=== ikeji/cyberdeck-index/schema/entry.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.invalid/cyberdeck/entry.schema.json",
  "title": "Entry",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "id",
    "title",
    "source",
    "images",
    "tags"
  ],
  "properties": {
    "schemaVersion": {
      "const": 1
    },
    "id": {
      "type": "string",
      "pattern": "^[0-9a-f]{24}$"
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "source": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url",
        "site"
      ],
      "properties": {
        "url": {
          "type": "string",
          "pattern": "^https?://"
        },
        "site": {
          "type": "string",
          "minLength": 1
        },
        "label": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "url",
          "site"
        ],
        "properties": {
          "url": {
            "type": "string",
            "pattern": "^https?://"
          },
          "site": {
            "type": "string"
          },
          "label": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    },
    "images": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/image"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "uniqueItems": true
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "uniqueItems": true
    },
    "comment": {
      "type": [
        "string",
        "null"
      ]
    },
    "scrapbox": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url",
        "created",
        "updated"
      ],
      "properties": {
        "url": {
          "type": "string",
          "pattern": "^https://scrapbox\\.io/"
        },
        "created": {
          "type": "string"
        },
        "updated": {
          "type": "string"
        },
        "views": {
          "type": "integer"
        },
        "thumbnail": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "addedAt": {
      "type": "string"
    }
  },
  "$defs": {
    "image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "origin",
        "originRaw",
        "status"
      ],
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        "origin": {
          "type": "string",
          "pattern": "^(https?://|local:)"
        },
        "originRaw": {
          "type": "string",
          "pattern": "^(https?://|local:)"
        },
        "status": {
          "enum": [
            "pending",
            "ok",
            "missing",
            "error"
          ]
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "mime": {
          "type": "string"
        },
        "files": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "thumb",
            "full"
          ],
          "properties": {
            "thumb": {
              "type": "string"
            },
            "full": {
              "type": "string"
            }
          }
        },
        "fetchedAt": {
          "type": "string"
        }
      },
      "if": {
        "properties": {
          "status": {
            "const": "ok"
          }
        }
      },
      "then": {
        "required": [
          "id",
          "files",
          "width",
          "height"
        ]
      }
    }
  }
}

=== ikeji/cyberdeck-index/data/entries/65e15818f9e1c80025f905b5.json
{
  "schemaVersion": 1,
  "id": "65e15818f9e1c80025f905b5",
  "title": "the A.R.M. Terminal",
  "source": {
    "url": "https://www.doscher.com/the-a-r-m-terminal/",
    "site": "web",
    "label": "the A.R.M. Terminal"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/65e1581a141bc700247cb7cd.png",
      "originRaw": "https://scrapbox.io/files/65e1581a141bc700247cb7cd.png",
      "id": "sha256:e47db84b369e915ac9c513b2e34f9ab015c8adc4b8b90705ba6351fbe2074c88",
      "status": "ok",
      "width": 1200,
      "height": 801,
      "mime": "image/webp",
      "files": {
        "thumb": "img/e4/e47db84b369e915ac9c513b2e34f9ab015c8adc4b8b90705ba6351fbe2074c88.thumb.webp",
        "full": "img/e4/e47db84b369e915ac9c513b2e34f9ab015c8adc4b8b90705ba6351fbe2074c88.webp"
      },
      "fetchedAt": "2026-10-02T18:05:12.590Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/the%20A.R.M.%20Terminal",
    "created": "2024-03-01T04:22:48.000Z",
    "updated": "2024-03-01T04:22:54.000Z",
    "views": 10,
    "thumbnail": "https://scrapbox.io/files/65e1581a141bc700247cb7cd.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/65e18cbfd7452e0024b72417.json
{
  "schemaVersion": 1,
  "id": "65e18cbfd7452e0024b72417",
  "title": "Xユーザーのtilde.industriesさん: 「The input system is based on the Cooke and Wheatstone telegraph, a device with 5 needles and an array of letters. When 2 needles point toward the same letter, it is registered~ t.co/IgBQwkDTAt」 / X",
  "source": {
    "url": "https://twitter.com/tildeindustries/status/1761075654181748894",
    "site": "twitter",
    "label": "Xユーザーのtilde.industriesさん: 「The input system is based on the Cooke and Wheatstone telegraph, a device with 5 needles and an array of letters. When 2 needles point toward the same letter, it is registered~ https://t.co/IgBQwkDTAt」 / X"
  },
  "links": [
    {
      "url": "https://twitter.com/tildeindustries/status/1758510044490957048?s=12",
      "label": null,
      "site": "twitter"
    },
    {
      "url": "https://en.wikipedia.org/wiki/Cooke_and_Wheatstone_telegraph",
      "label": null,
      "site": "web"
    }
  ],
  "images": [
    {
      "origin": "https://scrapbox.io/files/65e18cc260d50900231912bc.png",
      "originRaw": "https://scrapbox.io/files/65e18cc260d50900231912bc.png",
      "id": "sha256:5998d5b20c50aa40fd2bcc778ee243d6cba0c0d3bea7dd6d0bbf24badf9eb651",
      "status": "ok",
      "width": 680,
      "height": 536,
      "mime": "image/webp",
      "files": {
        "thumb": "img/59/5998d5b20c50aa40fd2bcc778ee243d6cba0c0d3bea7dd6d0bbf24badf9eb651.thumb.webp",
        "full": "img/59/5998d5b20c50aa40fd2bcc778ee243d6cba0c0d3bea7dd6d0bbf24badf9eb651.webp"
      },
      "fetchedAt": "2026-10-02T18:05:49.562Z"
    },
    {
      "origin": "https://scrapbox.io/files/65e18ce701b0550023e9df04.png",
      "originRaw": "https://scrapbox.io/files/65e18ce701b0550023e9df04.png",
      "id": "sha256:c308a5c90cd2df968bcc9ed58c1957892b5d0f21154fcbb79f1e7b198de29712",
      "status": "ok",
      "width": 675,
      "height": 900,
      "mime": "image/webp",
      "files": {
        "thumb": "img/c3/c308a5c90cd2df968bcc9ed58c1957892b5d0f21154fcbb79f1e7b198de29712.thumb.webp",
        "full": "img/c3/c308a5c90cd2df968bcc9ed58c1957892b5d0f21154fcbb79f1e7b198de29712.webp"
      },
      "fetchedAt": "2026-10-02T18:05:49.760Z"
    }
  ],
  "tags": [
    "IKeJIのおすすめ"
  ],
  "related": [],
  "comment": "入力方式はこれらしい。",
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/X%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%AEtilde.industries%E3%81%95%E3%82%93%3A%20%E3%80%8CThe%20input%20system%20is%20based%20on%20the%20Cooke%20and%20Wheatstone%20telegraph%2C%20a%20device%20with%205%20needles%20and%20an%20array%20of%20letters.%20When%202%20needles%20point%20toward%20the%20same%20letter%2C%20it%20is%20registered~%20t.co%2FIgBQwkDTAt%E3%80%8D%20%2F%20X",
    "created": "2024-03-01T08:07:28.000Z",
    "updated": "2026-05-08T14:38:18.000Z",
    "views": 22,
    "thumbnail": "https://scrapbox.io/files/65e18cc260d50900231912bc.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/6749b73a0c1a0604c7d42c7a.json
{
  "schemaVersion": 1,
  "id": "6749b73a0c1a0604c7d42c7a",
  "title": "Cyberdeck Handheld with Blackberry 9900 keyboard",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/1gue9i3/cyberdeck_handheld_with_blackberry_9900_keyboard/",
    "site": "reddit",
    "label": null
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/6749b775fd47425e2db96355.png",
      "originRaw": "https://scrapbox.io/files/6749b775fd47425e2db96355.png",
      "id": "sha256:2a1b31cd945574bc2050adbe21baf0f9292861690b0776d534603d214e40b929",
      "status": "ok",
      "width": 700,
      "height": 1095,
      "mime": "image/webp",
      "files": {
        "thumb": "img/2a/2a1b31cd945574bc2050adbe21baf0f9292861690b0776d534603d214e40b929.thumb.webp",
        "full": "img/2a/2a1b31cd945574bc2050adbe21baf0f9292861690b0776d534603d214e40b929.webp"
      },
      "fetchedAt": "2026-10-02T18:06:28.786Z"
    },
    {
      "origin": "https://scrapbox.io/files/6749b77de08db42b606063ff.png",
      "originRaw": "https://scrapbox.io/files/6749b77de08db42b606063ff.png",
      "id": "sha256:3eab5480b4c4ebb1e145adf5ddbb9c756920adfb03d5e34bb2954d61924d3aad",
      "status": "ok",
      "width": 602,
      "height": 814,
      "mime": "image/webp",
      "files": {
        "thumb": "img/3e/3eab5480b4c4ebb1e145adf5ddbb9c756920adfb03d5e34bb2954d61924d3aad.thumb.webp",
        "full": "img/3e/3eab5480b4c4ebb1e145adf5ddbb9c756920adfb03d5e34bb2954d61924d3aad.webp"
      },
      "fetchedAt": "2026-10-02T18:06:29.743Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/Cyberdeck%20Handheld%20with%20Blackberry%209900%20keyboard",
    "created": "2024-11-29T12:45:46.000Z",
    "updated": "2024-11-29T12:46:01.000Z",
    "views": 10,
    "thumbnail": "https://scrapbox.io/files/6749b775fd47425e2db96355.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/65e187224ac60f00242fce5d.json
{
  "schemaVersion": 1,
  "id": "65e187224ac60f00242fce5d",
  "title": "Raspberry pi deck I put together : r/cyberDeck",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/pxzrm9/raspberry_pi_deck_i_put_together/",
    "site": "reddit",
    "label": "Raspberry pi deck I put together : r/cyberDeck"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/65e187244b1ae800243a0b20.png",
      "originRaw": "https://scrapbox.io/files/65e187244b1ae800243a0b20.png",
      "id": "sha256:b95e6e5a58ec2ff9d89d6d915eb001c882b6a536a57c9e63b7055326d4da1db8",
      "status": "ok",
      "width": 1080,
      "height": 838,
      "mime": "image/webp",
      "files": {
        "thumb": "img/b9/b95e6e5a58ec2ff9d89d6d915eb001c882b6a536a57c9e63b7055326d4da1db8.thumb.webp",
        "full": "img/b9/b95e6e5a58ec2ff9d89d6d915eb001c882b6a536a57c9e63b7055326d4da1db8.webp"
      },
      "fetchedAt": "2026-10-02T18:05:37.380Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/Raspberry%20pi%20deck%20I%20put%20together%20%3A%20r%2FcyberDeck",
    "created": "2024-03-01T07:43:31.000Z",
    "updated": "2024-03-01T07:43:37.000Z",
    "views": 11,
    "thumbnail": "https://scrapbox.io/files/65e187244b1ae800243a0b20.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/69e243be497a50dbb9a27a31.json
{
  "schemaVersion": 1,
  "id": "69e243be497a50dbb9a27a31",
  "title": "My retro mini laptop style cyberdeck.",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/1s7pwi0/my_retro_mini_laptop_style_cyberdeck/",
    "site": "reddit",
    "label": null
  },
  "links": [],
  "images": [
    {
      "origin": "https://gyazo.com/40b681cfb06407b1faf0ce7c557a3b6f",
      "originRaw": "https://gyazo.com/40b681cfb06407b1faf0ce7c557a3b6f/raw",
      "id": "sha256:a1d6ec7df43b0c7d7e4fe6ada9e2c246dcb89b16ab22d081235040b4ea959c99",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/a1/a1d6ec7df43b0c7d7e4fe6ada9e2c246dcb89b16ab22d081235040b4ea959c99.thumb.webp",
        "full": "img/a1/a1d6ec7df43b0c7d7e4fe6ada9e2c246dcb89b16ab22d081235040b4ea959c99.webp"
      },
      "fetchedAt": "2026-10-03T07:53:35.775Z"
    },
    {
      "origin": "https://gyazo.com/f8d43f90eaf8715af98ccb5289f2d748",
      "originRaw": "https://gyazo.com/f8d43f90eaf8715af98ccb5289f2d748/raw",
      "id": "sha256:70910f2f182d20e51a7f13f7f2e68bada655b108c6129ee0298270ab6bd37f87",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/70/70910f2f182d20e51a7f13f7f2e68bada655b108c6129ee0298270ab6bd37f87.thumb.webp",
        "full": "img/70/70910f2f182d20e51a7f13f7f2e68bada655b108c6129ee0298270ab6bd37f87.webp"
      },
      "fetchedAt": "2026-10-03T07:53:37.607Z"
    },
    {
      "origin": "https://gyazo.com/e51bda5f1567739309fc103f3e3fabac",
      "originRaw": "https://gyazo.com/e51bda5f1567739309fc103f3e3fabac/raw",
      "id": "sha256:815e1407054b07a3d1793ddd381e1e09544a319b1e3d45d8ebf694388f15ff0b",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/81/815e1407054b07a3d1793ddd381e1e09544a319b1e3d45d8ebf694388f15ff0b.thumb.webp",
        "full": "img/81/815e1407054b07a3d1793ddd381e1e09544a319b1e3d45d8ebf694388f15ff0b.webp"
      },
      "fetchedAt": "2026-10-03T07:53:38.939Z"
    },
    {
      "origin": "https://gyazo.com/5be1dc3525c2469b333fccf7ea6a4472",
      "originRaw": "https://gyazo.com/5be1dc3525c2469b333fccf7ea6a4472/raw",
      "id": "sha256:26e98df03dc12989f006bacbe895aebfe1adbc30f31f699b9ab9749934b0e65d",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/26/26e98df03dc12989f006bacbe895aebfe1adbc30f31f699b9ab9749934b0e65d.thumb.webp",
        "full": "img/26/26e98df03dc12989f006bacbe895aebfe1adbc30f31f699b9ab9749934b0e65d.webp"
      },
      "fetchedAt": "2026-10-03T07:53:40.507Z"
    },
    {
      "origin": "https://gyazo.com/bed767acd2a56b774c57d2ba25f0e22c",
      "originRaw": "https://gyazo.com/bed767acd2a56b774c57d2ba25f0e22c/raw",
      "id": "sha256:cb322b6dbd9a464c7e3a99703c4f8d7fd2ee5223db3364750b584fd9c854534b",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/cb/cb322b6dbd9a464c7e3a99703c4f8d7fd2ee5223db3364750b584fd9c854534b.thumb.webp",
        "full": "img/cb/cb322b6dbd9a464c7e3a99703c4f8d7fd2ee5223db3364750b584fd9c854534b.webp"
      },
      "fetchedAt": "2026-10-03T07:53:42.032Z"
    },
    {
      "origin": "https://gyazo.com/6f24f03050833bc1a6e1f9feb3826212",
      "originRaw": "https://gyazo.com/6f24f03050833bc1a6e1f9feb3826212/raw",
      "id": "sha256:a2a694f80807a3026357e4f9e96118fbdf9af157e537957144e70508aede693f",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/a2/a2a694f80807a3026357e4f9e96118fbdf9af157e537957144e70508aede693f.thumb.webp",
        "full": "img/a2/a2a694f80807a3026357e4f9e96118fbdf9af157e537957144e70508aede693f.webp"
      },
      "fetchedAt": "2026-10-03T07:53:43.398Z"
    },
    {
      "origin": "https://gyazo.com/397b57e7a43dc7a35f154b0023263eca",
      "originRaw": "https://gyazo.com/397b57e7a43dc7a35f154b0023263eca/raw",
      "id": "sha256:cbcb162ec73cb5d2d809bbcd1b77f2896e7cb077d162ec16ad490cd03cda423b",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/cb/cbcb162ec73cb5d2d809bbcd1b77f2896e7cb077d162ec16ad490cd03cda423b.thumb.webp",
        "full": "img/cb/cbcb162ec73cb5d2d809bbcd1b77f2896e7cb077d162ec16ad490cd03cda423b.webp"
      },
      "fetchedAt": "2026-10-03T07:53:45.458Z"
    },
    {
      "origin": "https://gyazo.com/7d8f8772dc767df993c167f4067b8e2b",
      "originRaw": "https://gyazo.com/7d8f8772dc767df993c167f4067b8e2b/raw",
      "id": "sha256:2fd18e80dd87c205a3f8bc8b02f60c563f23b77286a182e0dfc9fa22afc6b43d",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/2f/2fd18e80dd87c205a3f8bc8b02f60c563f23b77286a182e0dfc9fa22afc6b43d.thumb.webp",
        "full": "img/2f/2fd18e80dd87c205a3f8bc8b02f60c563f23b77286a182e0dfc9fa22afc6b43d.webp"
      },
      "fetchedAt": "2026-10-03T07:53:47.185Z"
    },
    {
      "origin": "https://gyazo.com/dbb0d16672e9ca835ddb97bc2f8e701b",
      "originRaw": "https://gyazo.com/dbb0d16672e9ca835ddb97bc2f8e701b/raw",
      "id": "sha256:e4ba2b1416e8e69d4133e23165085dfab70c10c87f2effe27f7ba16bab74a3ac",
      "status": "ok",
      "width": 1080,
      "height": 813,
      "mime": "image/webp",
      "files": {
        "thumb": "img/e4/e4ba2b1416e8e69d4133e23165085dfab70c10c87f2effe27f7ba16bab74a3ac.thumb.webp",
        "full": "img/e4/e4ba2b1416e8e69d4133e23165085dfab70c10c87f2effe27f7ba16bab74a3ac.webp"
      },
      "fetchedAt": "2026-10-03T07:53:49.097Z"
    },
    {
      "origin": "https://gyazo.com/e813994f2a9088beeb842c1a2b59d7b9",
      "originRaw": "https://gyazo.com/e813994f2a9088beeb842c1a2b59d7b9/raw",
      "id": "sha256:0de8ffec83d66446a1ccd30f27b8be096f115b8a2388d3987670635d2b480502",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/0d/0de8ffec83d66446a1ccd30f27b8be096f115b8a2388d3987670635d2b480502.thumb.webp",
        "full": "img/0d/0de8ffec83d66446a1ccd30f27b8be096f115b8a2388d3987670635d2b480502.webp"
      },
      "fetchedAt": "2026-10-03T07:53:50.398Z"
    },
    {
      "origin": "https://gyazo.com/53e10c5a93c4f69c58deb56221bc9376",
      "originRaw": "https://gyazo.com/53e10c5a93c4f69c58deb56221bc9376/raw",
      "id": "sha256:bedd509f308e23fc09cd1aa52136aff35f94b0d5f331a100211d430c76a9043b",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/be/bedd509f308e23fc09cd1aa52136aff35f94b0d5f331a100211d430c76a9043b.thumb.webp",
        "full": "img/be/bedd509f308e23fc09cd1aa52136aff35f94b0d5f331a100211d430c76a9043b.webp"
      },
      "fetchedAt": "2026-10-03T07:53:52.501Z"
    },
    {
      "origin": "https://gyazo.com/64aee1609d66d6f6cfb3a433c98ead4f",
      "originRaw": "https://gyazo.com/64aee1609d66d6f6cfb3a433c98ead4f/raw",
      "id": "sha256:58e72f3ffd3ceb8c0cdeff31d562aa1c43ff82b0b13a03ec94e4a0e4799fac19",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/58/58e72f3ffd3ceb8c0cdeff31d562aa1c43ff82b0b13a03ec94e4a0e4799fac19.thumb.webp",
        "full": "img/58/58e72f3ffd3ceb8c0cdeff31d562aa1c43ff82b0b13a03ec94e4a0e4799fac19.webp"
      },
      "fetchedAt": "2026-10-03T07:53:55.031Z"
    },
    {
      "origin": "https://gyazo.com/7474dd0cf74a72c3007fbaa8eabf53c8",
      "originRaw": "https://gyazo.com/7474dd0cf74a72c3007fbaa8eabf53c8/raw",
      "id": "sha256:73e86d27f2db22558a3f92c1a198a8c0258929e85bab550011da0fb9e8d6df7b",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/73/73e86d27f2db22558a3f92c1a198a8c0258929e85bab550011da0fb9e8d6df7b.thumb.webp",
        "full": "img/73/73e86d27f2db22558a3f92c1a198a8c0258929e85bab550011da0fb9e8d6df7b.webp"
      },
      "fetchedAt": "2026-10-03T07:53:57.384Z"
    },
    {
      "origin": "https://gyazo.com/06e93b7b76ba10c3f42032e1ec023290",
      "originRaw": "https://gyazo.com/06e93b7b76ba10c3f42032e1ec023290/raw",
      "id": "sha256:f07222a0d2600869c6fa6dfeda5309168b756f158ad844c13708d0009488bbe3",
      "status": "ok",
      "width": 1080,
      "height": 1434,
      "mime": "image/webp",
      "files": {
        "thumb": "img/f0/f07222a0d2600869c6fa6dfeda5309168b756f158ad844c13708d0009488bbe3.thumb.webp",
        "full": "img/f0/f07222a0d2600869c6fa6dfeda5309168b756f158ad844c13708d0009488bbe3.webp"
      },
      "fetchedAt": "2026-10-03T07:53:58.674Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/My%20retro%20mini%20laptop%20style%20cyberdeck.",
    "created": "2026-04-17T14:29:24.000Z",
    "updated": "2026-04-17T14:30:31.000Z",
    "views": 7,
    "thumbnail": "https://gyazo.com/40b681cfb06407b1faf0ce7c557a3b6f/raw"
  }
}

=== ikeji/cyberdeck-index/data/entries/6606eaeaabf3d60024899dd7.json
{
  "schemaVersion": 1,
  "id": "6606eaeaabf3d60024899dd7",
  "title": "I finished building my first CyberDeck.... Again. : r/cyberDeck",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/1bl6wwm/i_finished_building_my_first_cyberdeck_again/",
    "site": "reddit",
    "label": "I finished building my first CyberDeck.... Again. : r/cyberDeck"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/6606eaf0eae247002525be76.png",
      "originRaw": "https://scrapbox.io/files/6606eaf0eae247002525be76.png",
      "id": "sha256:a41d96ee8c2d420ff1d4aee13869523f664610c5c2af4935889e74620c958d83",
      "status": "ok",
      "width": 1080,
      "height": 810,
      "mime": "image/webp",
      "files": {
        "thumb": "img/a4/a41d96ee8c2d420ff1d4aee13869523f664610c5c2af4935889e74620c958d83.thumb.webp",
        "full": "img/a4/a41d96ee8c2d420ff1d4aee13869523f664610c5c2af4935889e74620c958d83.webp"
      },
      "fetchedAt": "2026-10-02T18:05:56.662Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/I%20finished%20building%20my%20first%20CyberDeck....%20Again.%20%3A%20r%2FcyberDeck",
    "created": "2024-03-29T16:23:07.000Z",
    "updated": "2024-03-29T16:23:17.000Z",
    "views": 17,
    "thumbnail": "https://scrapbox.io/files/6606eaf0eae247002525be76.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/67b88fd8a935c2c23e6d3a74.json
{
  "schemaVersion": 1,
  "id": "67b88fd8a935c2c23e6d3a74",
  "title": "Schist01- A wrist mounted keyboard project",
  "source": {
    "url": "https://www.reddit.com/r/ErgoMechKeyboards/comments/1iqctqe/schist01_a_wrist_mounted_keyboard_project/",
    "site": "reddit",
    "label": "Schist01- A wrist mounted keyboard project : r/ErgoMechKeyboards"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/67b88fd94152b15f48b7967d.png",
      "originRaw": "https://scrapbox.io/files/67b88fd94152b15f48b7967d.png",
      "id": "sha256:49d8d2b1acf6393c29d82d64b879e548fd718b65a43255c87826df3d77d7a968",
      "status": "ok",
      "width": 1024,
      "height": 605,
      "mime": "image/webp",
      "files": {
        "thumb": "img/49/49d8d2b1acf6393c29d82d64b879e548fd718b65a43255c87826df3d77d7a968.thumb.webp",
        "full": "img/49/49d8d2b1acf6393c29d82d64b879e548fd718b65a43255c87826df3d77d7a968.webp"
      },
      "fetchedAt": "2026-10-02T18:06:43.555Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/Schist01-%20A%20wrist%20mounted%20keyboard%20project",
    "created": "2025-02-21T14:38:18.000Z",
    "updated": "2025-02-21T14:38:27.000Z",
    "views": 6,
    "thumbnail": "https://scrapbox.io/files/67b88fd94152b15f48b7967d.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/65e180f51e860f0024894ddd.json
{
  "schemaVersion": 1,
  "id": "65e180f51e860f0024894ddd",
  "title": "Maybe not a full-on cyberdeck, but proud of my first self-designed portable setup : r/cyberDeck",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/j07ya4/maybe_not_a_fullon_cyberdeck_but_proud_of_my/",
    "site": "reddit",
    "label": "Maybe not a full-on cyberdeck, but proud of my first self-designed portable setup : r/cyberDeck"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/65e180f83b74740023e64743.png",
      "originRaw": "https://scrapbox.io/files/65e180f83b74740023e64743.png",
      "id": "sha256:5f7715f33be8b6cdb044f3d6d1e28264be3ef99f28d7716a8b3c6cbf473494ac",
      "status": "ok",
      "width": 600,
      "height": 315,
      "mime": "image/webp",
      "files": {
        "thumb": "img/5f/5f7715f33be8b6cdb044f3d6d1e28264be3ef99f28d7716a8b3c6cbf473494ac.thumb.webp",
        "full": "img/5f/5f7715f33be8b6cdb044f3d6d1e28264be3ef99f28d7716a8b3c6cbf473494ac.webp"
      },
      "fetchedAt": "2026-10-02T18:05:23.138Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/Maybe%20not%20a%20full-on%20cyberdeck%2C%20but%20proud%20of%20my%20first%20self-designed%20portable%20setup%20%3A%20r%2FcyberDeck",
    "created": "2024-03-01T07:17:10.000Z",
    "updated": "2024-03-01T07:17:15.000Z",
    "views": 14,
    "thumbnail": "https://scrapbox.io/files/65e180f83b74740023e64743.png"
  }
}
