=== ikeji/cyberdeck-index/schema/entry.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.invalid/cyberdeck/entry.schema.json",
  "title": "Entry",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "id",
    "title",
    "source",
    "images",
    "tags"
  ],
  "properties": {
    "schemaVersion": {
      "const": 1
    },
    "id": {
      "type": "string",
      "pattern": "^[0-9a-f]{24}$"
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "source": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url",
        "site"
      ],
      "properties": {
        "url": {
          "type": "string",
          "pattern": "^https?://"
        },
        "site": {
          "type": "string",
          "minLength": 1
        },
        "label": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "url",
          "site"
        ],
        "properties": {
          "url": {
            "type": "string",
            "pattern": "^https?://"
          },
          "site": {
            "type": "string"
          },
          "label": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    },
    "images": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/image"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "uniqueItems": true
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "uniqueItems": true
    },
    "comment": {
      "type": [
        "string",
        "null"
      ]
    },
    "scrapbox": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "url",
        "created",
        "updated"
      ],
      "properties": {
        "url": {
          "type": "string",
          "pattern": "^https://scrapbox\\.io/"
        },
        "created": {
          "type": "string"
        },
        "updated": {
          "type": "string"
        },
        "views": {
          "type": "integer"
        },
        "thumbnail": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "addedAt": {
      "type": "string"
    }
  },
  "$defs": {
    "image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "origin",
        "originRaw",
        "status"
      ],
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        "origin": {
          "type": "string",
          "pattern": "^(https?://|local:)"
        },
        "originRaw": {
          "type": "string",
          "pattern": "^(https?://|local:)"
        },
        "status": {
          "enum": [
            "pending",
            "ok",
            "missing",
            "error"
          ]
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "mime": {
          "type": "string"
        },
        "files": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "thumb",
            "full"
          ],
          "properties": {
            "thumb": {
              "type": "string"
            },
            "full": {
              "type": "string"
            }
          }
        },
        "fetchedAt": {
          "type": "string"
        }
      },
      "if": {
        "properties": {
          "status": {
            "const": "ok"
          }
        }
      },
      "then": {
        "required": [
          "id",
          "files",
          "width",
          "height"
        ]
      }
    }
  }
}

=== ikeji/cyberdeck-index/data/entries/693c29831ef7600801f55121.json
{
  "schemaVersion": 1,
  "id": "693c29831ef7600801f55121",
  "title": "Field Terminal V2 - Custom Rugged Cyberdeck with 14Ah battery & Active Cooling",
  "source": {
    "url": "https://www.reddit.com/r/RASPBERRY_PI_PROJECTS/comments/1pb7fge/field_terminal_v2_custom_rugged_cyberdeck_with/",
    "site": "reddit",
    "label": null
  },
  "links": [],
  "images": [
    {
      "origin": "https://gyazo.com/8d96e0d7613ea33fd5878aab1ffe6969",
      "originRaw": "https://gyazo.com/8d96e0d7613ea33fd5878aab1ffe6969/raw",
      "id": "sha256:6f8214e3ce2794631d83105b94668fab2a578c2926fcf1031ec4c21839e47e70",
      "status": "ok",
      "width": 1080,
      "height": 1161,
      "mime": "image/webp",
      "files": {
        "thumb": "img/6f/6f8214e3ce2794631d83105b94668fab2a578c2926fcf1031ec4c21839e47e70.thumb.webp",
        "full": "img/6f/6f8214e3ce2794631d83105b94668fab2a578c2926fcf1031ec4c21839e47e70.webp"
      },
      "fetchedAt": "2026-10-03T07:50:10.093Z"
    },
    {
      "origin": "https://gyazo.com/5fa6f5e9c2a1c569992d159a27888576",
      "originRaw": "https://gyazo.com/5fa6f5e9c2a1c569992d159a27888576/raw",
      "id": "sha256:c746620088489a942289b2d63694b23733009b77c067f462c0fe2c696a3227bd",
      "status": "ok",
      "width": 1080,
      "height": 810,
      "mime": "image/webp",
      "files": {
        "thumb": "img/c7/c746620088489a942289b2d63694b23733009b77c067f462c0fe2c696a3227bd.thumb.webp",
        "full": "img/c7/c746620088489a942289b2d63694b23733009b77c067f462c0fe2c696a3227bd.webp"
      },
      "fetchedAt": "2026-10-03T07:50:12.010Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/Field%20Terminal%20V2%20-%20Custom%20Rugged%20Cyberdeck%20with%2014Ah%20battery%20%26%20Active%20Cooling",
    "created": "2025-12-12T14:41:09.000Z",
    "updated": "2025-12-12T14:41:35.000Z",
    "views": 5,
    "thumbnail": "https://gyazo.com/8d96e0d7613ea33fd5878aab1ffe6969/raw"
  }
}

=== ikeji/cyberdeck-index/data/entries/698f2c5be911234b09fc5226.json
{
  "schemaVersion": 1,
  "id": "698f2c5be911234b09fc5226",
  "title": "I present the gearmunicator",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/1quz906/i_present_the_gearmunicator/",
    "site": "reddit",
    "label": null
  },
  "links": [],
  "images": [
    {
      "origin": "https://gyazo.com/63f2e9ee6462861828285f4532b88e59",
      "originRaw": "https://gyazo.com/63f2e9ee6462861828285f4532b88e59/raw",
      "id": "sha256:cc268822dee4b81e081380eabcd98613e01d22b267d3f795c2db68fbd42de635",
      "status": "ok",
      "width": 640,
      "height": 853,
      "mime": "image/webp",
      "files": {
        "thumb": "img/cc/cc268822dee4b81e081380eabcd98613e01d22b267d3f795c2db68fbd42de635.thumb.webp",
        "full": "img/cc/cc268822dee4b81e081380eabcd98613e01d22b267d3f795c2db68fbd42de635.webp"
      },
      "fetchedAt": "2026-10-03T07:51:35.187Z"
    },
    {
      "origin": "https://gyazo.com/d736d658a09d2ff494f04c7ecf2f5ada",
      "originRaw": "https://gyazo.com/d736d658a09d2ff494f04c7ecf2f5ada/raw",
      "id": "sha256:300b15fb876ecfa7ddf85f18126e6684bf424da582aa750855393449f88acc2f",
      "status": "ok",
      "width": 1080,
      "height": 1440,
      "mime": "image/webp",
      "files": {
        "thumb": "img/30/300b15fb876ecfa7ddf85f18126e6684bf424da582aa750855393449f88acc2f.thumb.webp",
        "full": "img/30/300b15fb876ecfa7ddf85f18126e6684bf424da582aa750855393449f88acc2f.webp"
      },
      "fetchedAt": "2026-10-03T07:51:37.365Z"
    },
    {
      "origin": "https://gyazo.com/01edf1108153073cf70e379e0a9fe21d",
      "originRaw": "https://gyazo.com/01edf1108153073cf70e379e0a9fe21d/raw",
      "id": "sha256:52d016d3ccb63d454d330e57e3e64588251f2ac5cc1de1318826fd3c171ae82f",
      "status": "ok",
      "width": 1080,
      "height": 1440,
      "mime": "image/webp",
      "files": {
        "thumb": "img/52/52d016d3ccb63d454d330e57e3e64588251f2ac5cc1de1318826fd3c171ae82f.thumb.webp",
        "full": "img/52/52d016d3ccb63d454d330e57e3e64588251f2ac5cc1de1318826fd3c171ae82f.webp"
      },
      "fetchedAt": "2026-10-03T07:51:39.118Z"
    },
    {
      "origin": "https://gyazo.com/f45eb91d5fc16eeb880b6c0f5b8c84d4",
      "originRaw": "https://gyazo.com/f45eb91d5fc16eeb880b6c0f5b8c84d4/raw",
      "id": "sha256:6f37063d5901a0793f9c0ffa2ad8b0c56e2d3f99af1f5799c120a5aaccf217e3",
      "status": "ok",
      "width": 1080,
      "height": 1440,
      "mime": "image/webp",
      "files": {
        "thumb": "img/6f/6f37063d5901a0793f9c0ffa2ad8b0c56e2d3f99af1f5799c120a5aaccf217e3.thumb.webp",
        "full": "img/6f/6f37063d5901a0793f9c0ffa2ad8b0c56e2d3f99af1f5799c120a5aaccf217e3.webp"
      },
      "fetchedAt": "2026-10-03T07:51:41.410Z"
    },
    {
      "origin": "https://gyazo.com/d4bbb15c67ce5754d5716ffbdeaab7ea",
      "originRaw": "https://gyazo.com/d4bbb15c67ce5754d5716ffbdeaab7ea/raw",
      "id": "sha256:cdf97eb214f1b08f6a4b8e28d682c0e84b4f337bada11447802e98f2b94585a8",
      "status": "ok",
      "width": 1080,
      "height": 1440,
      "mime": "image/webp",
      "files": {
        "thumb": "img/cd/cdf97eb214f1b08f6a4b8e28d682c0e84b4f337bada11447802e98f2b94585a8.thumb.webp",
        "full": "img/cd/cdf97eb214f1b08f6a4b8e28d682c0e84b4f337bada11447802e98f2b94585a8.webp"
      },
      "fetchedAt": "2026-10-03T07:51:43.529Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/I%20present%20the%20gearmunicator",
    "created": "2026-02-13T13:51:25.000Z",
    "updated": "2026-02-13T13:52:16.000Z",
    "views": 8,
    "thumbnail": "https://gyazo.com/63f2e9ee6462861828285f4532b88e59/raw"
  }
}

=== ikeji/cyberdeck-index/data/entries/65e18e7260aaff0024bb24a2.json
{
  "schemaVersion": 1,
  "id": "65e18e7260aaff0024bb24a2",
  "title": "Building A Mouse That’s Also A Computer | Hackaday",
  "source": {
    "url": "https://hackaday.com/2024/01/25/building-a-mouse-thats-also-a-computer/",
    "site": "hackaday",
    "label": "Building A Mouse That’s Also A Computer | Hackaday"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/65e18e74d7452e0024b73a27.png",
      "originRaw": "https://scrapbox.io/files/65e18e74d7452e0024b73a27.png",
      "id": "sha256:a339e2727b4a677757dc2c7bb0476c662f9de3b896972e2513ccd56867be2171",
      "status": "ok",
      "width": 800,
      "height": 450,
      "mime": "image/webp",
      "files": {
        "thumb": "img/a3/a339e2727b4a677757dc2c7bb0476c662f9de3b896972e2513ccd56867be2171.thumb.webp",
        "full": "img/a3/a339e2727b4a677757dc2c7bb0476c662f9de3b896972e2513ccd56867be2171.webp"
      },
      "fetchedAt": "2026-10-02T18:05:52.788Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/Building%20A%20Mouse%20That%E2%80%99s%20Also%20A%20Computer%20%7C%20Hackaday",
    "created": "2024-03-01T08:14:43.000Z",
    "updated": "2024-03-01T08:14:48.000Z",
    "views": 14,
    "thumbnail": "https://scrapbox.io/files/65e18e74d7452e0024b73a27.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/66cad74a1c2a22001daaf367.json
{
  "schemaVersion": 1,
  "id": "66cad74a1c2a22001daaf367",
  "title": "My Fully 3D Printed Cyberdeck : r/cyberDeck",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/1dfg34e/my_fully_3d_printed_cyberdeck/",
    "site": "reddit",
    "label": "My Fully 3D Printed Cyberdeck : r/cyberDeck"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/66cad74d8f8fc7001dc90cff.png",
      "originRaw": "https://scrapbox.io/files/66cad74d8f8fc7001dc90cff.png",
      "id": "sha256:fcf23a8a3263b4782f55e55b88f4c4f4ee1cbb580595d8f6cebef5e89c4612bb",
      "status": "ok",
      "width": 1080,
      "height": 660,
      "mime": "image/webp",
      "files": {
        "thumb": "img/fc/fcf23a8a3263b4782f55e55b88f4c4f4ee1cbb580595d8f6cebef5e89c4612bb.thumb.webp",
        "full": "img/fc/fcf23a8a3263b4782f55e55b88f4c4f4ee1cbb580595d8f6cebef5e89c4612bb.webp"
      },
      "fetchedAt": "2026-10-02T18:06:15.929Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/My%20Fully%203D%20Printed%20Cyberdeck%20%3A%20r%2FcyberDeck",
    "created": "2024-08-25T07:03:39.000Z",
    "updated": "2024-08-25T07:03:44.000Z",
    "views": 5,
    "thumbnail": "https://scrapbox.io/files/66cad74d8f8fc7001dc90cff.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/65e189f826c67e00244faffb.json
{
  "schemaVersion": 1,
  "id": "65e189f826c67e00244faffb",
  "title": "Xユーザーのmimi UMPCさん: 「自作ポケコン3号機が完成！ 充電モジュールの仕様に悩まされたけど何とか解決して良かった〜♪中身vim4なので2号機(黒PiZero2W)よりサクサク動作します 今回は縦長なので落下防止用にストラップホールを付けました |･ω･`)レトロフューチャー万歳☆ t.co/TeJnpkppwz」 / X",
  "source": {
    "url": "https://twitter.com/mimi_umpc/status/1720671959326048327",
    "site": "twitter",
    "label": "Xユーザーのmimi_UMPCさん: 「自作ポケコン3号機が完成！ 充電モジュールの仕様に悩まされたけど何とか解決して良かった〜♪中身vim4なので2号機(黒PiZero2W)よりサクサク動作します 今回は縦長なので落下防止用にストラップホールを付けました |･ω･`)レトロフューチャー万歳☆ https://t.co/TeJnpkppwz」 / X"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/65e189fde25eb000256e5843.png",
      "originRaw": "https://scrapbox.io/files/65e189fde25eb000256e5843.png",
      "id": "sha256:9a6c9b1e84953171374a23d3473df2ff3c27f97176d7e0c720519986fdde2a55",
      "status": "ok",
      "width": 1600,
      "height": 1600,
      "mime": "image/webp",
      "files": {
        "thumb": "img/9a/9a6c9b1e84953171374a23d3473df2ff3c27f97176d7e0c720519986fdde2a55.thumb.webp",
        "full": "img/9a/9a6c9b1e84953171374a23d3473df2ff3c27f97176d7e0c720519986fdde2a55.webp"
      },
      "fetchedAt": "2026-10-02T18:05:45.367Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/X%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%AEmimi%20UMPC%E3%81%95%E3%82%93%3A%20%E3%80%8C%E8%87%AA%E4%BD%9C%E3%83%9D%E3%82%B1%E3%82%B3%E3%83%B33%E5%8F%B7%E6%A9%9F%E3%81%8C%E5%AE%8C%E6%88%90%EF%BC%81%20%E5%85%85%E9%9B%BB%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%AE%E4%BB%95%E6%A7%98%E3%81%AB%E6%82%A9%E3%81%BE%E3%81%95%E3%82%8C%E3%81%9F%E3%81%91%E3%81%A9%E4%BD%95%E3%81%A8%E3%81%8B%E8%A7%A3%E6%B1%BA%E3%81%97%E3%81%A6%E8%89%AF%E3%81%8B%E3%81%A3%E3%81%9F%E3%80%9C%E2%99%AA%E4%B8%AD%E8%BA%ABvim4%E3%81%AA%E3%81%AE%E3%81%A72%E5%8F%B7%E6%A9%9F(%E9%BB%92PiZero2W)%E3%82%88%E3%82%8A%E3%82%B5%E3%82%AF%E3%82%B5%E3%82%AF%E5%8B%95%E4%BD%9C%E3%81%97%E3%81%BE%E3%81%99%20%E4%BB%8A%E5%9B%9E%E3%81%AF%E7%B8%A6%E9%95%B7%E3%81%AA%E3%81%AE%E3%81%A7%E8%90%BD%E4%B8%8B%E9%98%B2%E6%AD%A2%E7%94%A8%E3%81%AB%E3%82%B9%E3%83%88%E3%83%A9%E3%83%83%E3%83%97%E3%83%9B%E3%83%BC%E3%83%AB%E3%82%92%E4%BB%98%E3%81%91%E3%81%BE%E3%81%97%E3%81%9F%20%7C%EF%BD%A5%CF%89%EF%BD%A5%60)%E3%83%AC%E3%83%88%E3%83%AD%E3%83%95%E3%83%A5%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC%E4%B8%87%E6%AD%B3%E2%98%86%20t.co%2FTeJnpkppwz%E3%80%8D%20%2F%20X",
    "created": "2024-03-01T07:55:37.000Z",
    "updated": "2024-03-01T07:55:47.000Z",
    "views": 6,
    "thumbnail": "https://scrapbox.io/files/65e189fde25eb000256e5843.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/65e186bed22de50024d6905e.json
{
  "schemaVersion": 1,
  "id": "65e186bed22de50024d6905e",
  "title": "My 'Sardautari', a 3D printed Raspberry Pi laptop fit for any Burseg in the field! : r/cyberDeck",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/jurk4d/my_sardautari_a_3d_printed_raspberry_pi_laptop/",
    "site": "reddit",
    "label": "My 'Sardautari', a 3D printed Raspberry Pi laptop fit for any Burseg in the field! : r/cyberDeck"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/65e186c183075b0024b10056.png",
      "originRaw": "https://scrapbox.io/files/65e186c183075b0024b10056.png",
      "id": "sha256:c7297d5eaded66b7130d1b5303dccae2ed199b519647545f8c8c1d145ef8cb5b",
      "status": "ok",
      "width": 1080,
      "height": 810,
      "mime": "image/webp",
      "files": {
        "thumb": "img/c7/c7297d5eaded66b7130d1b5303dccae2ed199b519647545f8c8c1d145ef8cb5b.thumb.webp",
        "full": "img/c7/c7297d5eaded66b7130d1b5303dccae2ed199b519647545f8c8c1d145ef8cb5b.webp"
      },
      "fetchedAt": "2026-10-02T18:05:34.873Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/My%20'Sardautari'%2C%20a%203D%20printed%20Raspberry%20Pi%20laptop%20fit%20for%20any%20Burseg%20in%20the%20field!%20%3A%20r%2FcyberDeck",
    "created": "2024-03-01T07:41:50.000Z",
    "updated": "2024-03-01T07:41:57.000Z",
    "views": 9,
    "thumbnail": "https://scrapbox.io/files/65e186c183075b0024b10056.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/679cdba6e25d9ee046af2011.json
{
  "schemaVersion": 1,
  "id": "679cdba6e25d9ee046af2011",
  "title": "New boy joins the family : r/cyberDeck",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/1i0ls9h/new_boy_joins_the_family/",
    "site": "reddit",
    "label": "New boy joins the family : r/cyberDeck"
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/679cdba924f15a7e85d73271.png",
      "originRaw": "https://scrapbox.io/files/679cdba924f15a7e85d73271.png",
      "id": "sha256:3706a5a74b57850764b0e6fcb53bebc984d1050604de7019c7736057c5e290db",
      "status": "ok",
      "width": 1080,
      "height": 1440,
      "mime": "image/webp",
      "files": {
        "thumb": "img/37/3706a5a74b57850764b0e6fcb53bebc984d1050604de7019c7736057c5e290db.thumb.webp",
        "full": "img/37/3706a5a74b57850764b0e6fcb53bebc984d1050604de7019c7736057c5e290db.webp"
      },
      "fetchedAt": "2026-10-02T18:06:36.468Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/New%20boy%20joins%20the%20family%20%3A%20r%2FcyberDeck",
    "created": "2025-01-31T14:18:14.000Z",
    "updated": "2025-01-31T14:18:23.000Z",
    "views": 3,
    "thumbnail": "https://scrapbox.io/files/679cdba924f15a7e85d73271.png"
  }
}

=== ikeji/cyberdeck-index/data/entries/67127148d17c8ff0483d4cc1.json
{
  "schemaVersion": 1,
  "id": "67127148d17c8ff0483d4cc1",
  "title": "Can someone make me this? I'll buy.",
  "source": {
    "url": "https://www.reddit.com/r/cyberDeck/comments/1g2j1f1/can_someone_make_me_this_ill_buy/",
    "site": "reddit",
    "label": null
  },
  "links": [],
  "images": [
    {
      "origin": "https://scrapbox.io/files/6712717a8482f6b58adb5f32.png",
      "originRaw": "https://scrapbox.io/files/6712717a8482f6b58adb5f32.png",
      "id": "sha256:c273227b37919eb413c7cf050a2ab01792fad583285a9594e7d4bedd88a84ff9",
      "status": "ok",
      "width": 500,
      "height": 1050,
      "mime": "image/webp",
      "files": {
        "thumb": "img/c2/c273227b37919eb413c7cf050a2ab01792fad583285a9594e7d4bedd88a84ff9.thumb.webp",
        "full": "img/c2/c273227b37919eb413c7cf050a2ab01792fad583285a9594e7d4bedd88a84ff9.webp"
      },
      "fetchedAt": "2026-10-02T18:06:25.977Z"
    }
  ],
  "tags": [],
  "related": [],
  "comment": null,
  "scrapbox": {
    "url": "https://scrapbox.io/CYBERDECK/Can%20someone%20make%20me%20this%3F%20I'll%20buy.",
    "created": "2024-10-18T14:32:26.000Z",
    "updated": "2024-10-18T14:32:39.000Z",
    "views": 5,
    "thumbnail": "https://scrapbox.io/files/6712717a8482f6b58adb5f32.png"
  }
}
